name: Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/update.yaml'
    - 'update.py'
    - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/update.yaml'
    - 'update.py'
    - 'requirements.txt'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 6 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: "Run update.py"
      run: |
        mkdir -p data/lpp
        mkdir -p data/marprom
        python update.py 

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -la data/*
        git status
        git diff

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: "Publish data changes to git"
      if: github.repository == 'openstreetmap-si/bus-routes-osm-lpp' && github.ref == 'refs/heads/main'
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: "Data update 🤖"
        files: data/*
        name: 'github-actions[bot]'
        email: '41898282+github-actions[bot]@users.noreply.github.com'
